/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheorieIndexRouteImport } from './routes/theorie.index'
import { Route as ExercicesIndexRouteImport } from './routes/exercices.index'
import { Route as TheorieChapterIdRouteImport } from './routes/theorie.$chapterId'
import { Route as ExercicesSessionSlugRouteImport } from './routes/exercices.$sessionSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheorieIndexRoute = TheorieIndexRouteImport.update({
  id: '/theorie/',
  path: '/theorie/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesIndexRoute = ExercicesIndexRouteImport.update({
  id: '/exercices/',
  path: '/exercices/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheorieChapterIdRoute = TheorieChapterIdRouteImport.update({
  id: '/theorie/$chapterId',
  path: '/theorie/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesSessionSlugRoute = ExercicesSessionSlugRouteImport.update({
  id: '/exercices/$sessionSlug',
  path: '/exercices/$sessionSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercices/$sessionSlug': typeof ExercicesSessionSlugRoute
  '/theorie/$chapterId': typeof TheorieChapterIdRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/theorie/': typeof TheorieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercices/$sessionSlug': typeof ExercicesSessionSlugRoute
  '/theorie/$chapterId': typeof TheorieChapterIdRoute
  '/exercices': typeof ExercicesIndexRoute
  '/theorie': typeof TheorieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercices/$sessionSlug': typeof ExercicesSessionSlugRoute
  '/theorie/$chapterId': typeof TheorieChapterIdRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/theorie/': typeof TheorieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercices/$sessionSlug'
    | '/theorie/$chapterId'
    | '/exercices/'
    | '/theorie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercices/$sessionSlug'
    | '/theorie/$chapterId'
    | '/exercices'
    | '/theorie'
  id:
    | '__root__'
    | '/'
    | '/exercices/$sessionSlug'
    | '/theorie/$chapterId'
    | '/exercices/'
    | '/theorie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercicesSessionSlugRoute: typeof ExercicesSessionSlugRoute
  TheorieChapterIdRoute: typeof TheorieChapterIdRoute
  ExercicesIndexRoute: typeof ExercicesIndexRoute
  TheorieIndexRoute: typeof TheorieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theorie/': {
      id: '/theorie/'
      path: '/theorie'
      fullPath: '/theorie/'
      preLoaderRoute: typeof TheorieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/': {
      id: '/exercices/'
      path: '/exercices'
      fullPath: '/exercices/'
      preLoaderRoute: typeof ExercicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theorie/$chapterId': {
      id: '/theorie/$chapterId'
      path: '/theorie/$chapterId'
      fullPath: '/theorie/$chapterId'
      preLoaderRoute: typeof TheorieChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/$sessionSlug': {
      id: '/exercices/$sessionSlug'
      path: '/exercices/$sessionSlug'
      fullPath: '/exercices/$sessionSlug'
      preLoaderRoute: typeof ExercicesSessionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercicesSessionSlugRoute: ExercicesSessionSlugRoute,
  TheorieChapterIdRoute: TheorieChapterIdRoute,
  ExercicesIndexRoute: ExercicesIndexRoute,
  TheorieIndexRoute: TheorieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
