/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheorieIndexRouteImport } from './routes/theorie.index'
import { Route as ExercicesIndexRouteImport } from './routes/exercices.index'
import { Route as CourseSlugIndexRouteImport } from './routes/$courseSlug.index'
import { Route as TheorieChapterIdRouteImport } from './routes/theorie.$chapterId'
import { Route as ExercicesSessionSlugRouteImport } from './routes/exercices.$sessionSlug'
import { Route as CourseSlugTheorieIndexRouteImport } from './routes/$courseSlug.theorie.index'
import { Route as CourseSlugExercicesIndexRouteImport } from './routes/$courseSlug.exercices.index'
import { Route as CourseSlugTheorieChapterIdRouteImport } from './routes/$courseSlug.theorie.$chapterId'
import { Route as CourseSlugExercicesSessionSlugRouteImport } from './routes/$courseSlug.exercices.$sessionSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheorieIndexRoute = TheorieIndexRouteImport.update({
  id: '/theorie/',
  path: '/theorie/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesIndexRoute = ExercicesIndexRouteImport.update({
  id: '/exercices/',
  path: '/exercices/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugIndexRoute = CourseSlugIndexRouteImport.update({
  id: '/$courseSlug/',
  path: '/$courseSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheorieChapterIdRoute = TheorieChapterIdRouteImport.update({
  id: '/theorie/$chapterId',
  path: '/theorie/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesSessionSlugRoute = ExercicesSessionSlugRouteImport.update({
  id: '/exercices/$sessionSlug',
  path: '/exercices/$sessionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugTheorieIndexRoute = CourseSlugTheorieIndexRouteImport.update({
  id: '/$courseSlug/theorie/',
  path: '/$courseSlug/theorie/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugExercicesIndexRoute =
  CourseSlugExercicesIndexRouteImport.update({
    id: '/$courseSlug/exercices/',
    path: '/$courseSlug/exercices/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseSlugTheorieChapterIdRoute =
  CourseSlugTheorieChapterIdRouteImport.update({
    id: '/$courseSlug/theorie/$chapterId',
    path: '/$courseSlug/theorie/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseSlugExercicesSessionSlugRoute =
  CourseSlugExercicesSessionSlugRouteImport.update({
    id: '/$courseSlug/exercices/$sessionSlug',
    path: '/$courseSlug/exercices/$sessionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercices/$sessionSlug': typeof ExercicesSessionSlugRoute
  '/theorie/$chapterId': typeof TheorieChapterIdRoute
  '/$courseSlug/': typeof CourseSlugIndexRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/theorie/': typeof TheorieIndexRoute
  '/$courseSlug/exercices/$sessionSlug': typeof CourseSlugExercicesSessionSlugRoute
  '/$courseSlug/theorie/$chapterId': typeof CourseSlugTheorieChapterIdRoute
  '/$courseSlug/exercices/': typeof CourseSlugExercicesIndexRoute
  '/$courseSlug/theorie/': typeof CourseSlugTheorieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercices/$sessionSlug': typeof ExercicesSessionSlugRoute
  '/theorie/$chapterId': typeof TheorieChapterIdRoute
  '/$courseSlug': typeof CourseSlugIndexRoute
  '/exercices': typeof ExercicesIndexRoute
  '/theorie': typeof TheorieIndexRoute
  '/$courseSlug/exercices/$sessionSlug': typeof CourseSlugExercicesSessionSlugRoute
  '/$courseSlug/theorie/$chapterId': typeof CourseSlugTheorieChapterIdRoute
  '/$courseSlug/exercices': typeof CourseSlugExercicesIndexRoute
  '/$courseSlug/theorie': typeof CourseSlugTheorieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercices/$sessionSlug': typeof ExercicesSessionSlugRoute
  '/theorie/$chapterId': typeof TheorieChapterIdRoute
  '/$courseSlug/': typeof CourseSlugIndexRoute
  '/exercices/': typeof ExercicesIndexRoute
  '/theorie/': typeof TheorieIndexRoute
  '/$courseSlug/exercices/$sessionSlug': typeof CourseSlugExercicesSessionSlugRoute
  '/$courseSlug/theorie/$chapterId': typeof CourseSlugTheorieChapterIdRoute
  '/$courseSlug/exercices/': typeof CourseSlugExercicesIndexRoute
  '/$courseSlug/theorie/': typeof CourseSlugTheorieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercices/$sessionSlug'
    | '/theorie/$chapterId'
    | '/$courseSlug/'
    | '/exercices/'
    | '/theorie/'
    | '/$courseSlug/exercices/$sessionSlug'
    | '/$courseSlug/theorie/$chapterId'
    | '/$courseSlug/exercices/'
    | '/$courseSlug/theorie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercices/$sessionSlug'
    | '/theorie/$chapterId'
    | '/$courseSlug'
    | '/exercices'
    | '/theorie'
    | '/$courseSlug/exercices/$sessionSlug'
    | '/$courseSlug/theorie/$chapterId'
    | '/$courseSlug/exercices'
    | '/$courseSlug/theorie'
  id:
    | '__root__'
    | '/'
    | '/exercices/$sessionSlug'
    | '/theorie/$chapterId'
    | '/$courseSlug/'
    | '/exercices/'
    | '/theorie/'
    | '/$courseSlug/exercices/$sessionSlug'
    | '/$courseSlug/theorie/$chapterId'
    | '/$courseSlug/exercices/'
    | '/$courseSlug/theorie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercicesSessionSlugRoute: typeof ExercicesSessionSlugRoute
  TheorieChapterIdRoute: typeof TheorieChapterIdRoute
  CourseSlugIndexRoute: typeof CourseSlugIndexRoute
  ExercicesIndexRoute: typeof ExercicesIndexRoute
  TheorieIndexRoute: typeof TheorieIndexRoute
  CourseSlugExercicesSessionSlugRoute: typeof CourseSlugExercicesSessionSlugRoute
  CourseSlugTheorieChapterIdRoute: typeof CourseSlugTheorieChapterIdRoute
  CourseSlugExercicesIndexRoute: typeof CourseSlugExercicesIndexRoute
  CourseSlugTheorieIndexRoute: typeof CourseSlugTheorieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theorie/': {
      id: '/theorie/'
      path: '/theorie'
      fullPath: '/theorie/'
      preLoaderRoute: typeof TheorieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/': {
      id: '/exercices/'
      path: '/exercices'
      fullPath: '/exercices/'
      preLoaderRoute: typeof ExercicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/': {
      id: '/$courseSlug/'
      path: '/$courseSlug'
      fullPath: '/$courseSlug/'
      preLoaderRoute: typeof CourseSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theorie/$chapterId': {
      id: '/theorie/$chapterId'
      path: '/theorie/$chapterId'
      fullPath: '/theorie/$chapterId'
      preLoaderRoute: typeof TheorieChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/$sessionSlug': {
      id: '/exercices/$sessionSlug'
      path: '/exercices/$sessionSlug'
      fullPath: '/exercices/$sessionSlug'
      preLoaderRoute: typeof ExercicesSessionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/theorie/': {
      id: '/$courseSlug/theorie/'
      path: '/$courseSlug/theorie'
      fullPath: '/$courseSlug/theorie/'
      preLoaderRoute: typeof CourseSlugTheorieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/exercices/': {
      id: '/$courseSlug/exercices/'
      path: '/$courseSlug/exercices'
      fullPath: '/$courseSlug/exercices/'
      preLoaderRoute: typeof CourseSlugExercicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/theorie/$chapterId': {
      id: '/$courseSlug/theorie/$chapterId'
      path: '/$courseSlug/theorie/$chapterId'
      fullPath: '/$courseSlug/theorie/$chapterId'
      preLoaderRoute: typeof CourseSlugTheorieChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/exercices/$sessionSlug': {
      id: '/$courseSlug/exercices/$sessionSlug'
      path: '/$courseSlug/exercices/$sessionSlug'
      fullPath: '/$courseSlug/exercices/$sessionSlug'
      preLoaderRoute: typeof CourseSlugExercicesSessionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercicesSessionSlugRoute: ExercicesSessionSlugRoute,
  TheorieChapterIdRoute: TheorieChapterIdRoute,
  CourseSlugIndexRoute: CourseSlugIndexRoute,
  ExercicesIndexRoute: ExercicesIndexRoute,
  TheorieIndexRoute: TheorieIndexRoute,
  CourseSlugExercicesSessionSlugRoute: CourseSlugExercicesSessionSlugRoute,
  CourseSlugTheorieChapterIdRoute: CourseSlugTheorieChapterIdRoute,
  CourseSlugExercicesIndexRoute: CourseSlugExercicesIndexRoute,
  CourseSlugTheorieIndexRoute: CourseSlugTheorieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
